### ISSUE TITLE
Work on one-page HTML Reference Manuals

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-day#14]
R Core member @deepayan has been working on generating one-page HTML reference manuals for CRAN packages. Eventually these may replace the PDF reference manuals on CRAN, but there are still some issues to be ironed out.

A preview is available at https://deepayan.github.io/r-refmans/ - this will be updated before R Dev Day @ PLUS.

Some Dev Day Tasks:

1. Check for failures against WCAG 2.2 AA
    - propose changes to fix above (patches of HTML/CSS files)
2. Review the generated pages to find issues
    - Incorrect links. Known examples include  Rd cross references which are not "anchored", i.e., do not explicitly specify the package of the topic linked to. 
    - Problems related to macros. Known examples include packages that use mathjaxr.

The issues page of the [r-refmans repo](https://github.com/deepayan/r-refmans/ ) can be used to make good reports of any problems identified, or to suggest improvements for consideration by Deepayan/the CRAN Team.

**Comment by EllaKaye** [comment]
This is an excellent project, to move away from PDF manuals to HTML ones!

I had a quick flick through some of the manuals on <https://deepayan.github.io/r-refmans/> and noted an issue. Lifecycle badges aren't rendered, e.g. at <https://deepayan.github.io/r-refmans/dplyr.html#add_rownames>. They appear as a small rectangle with a question mark in a blue box. These boxes are links and they resolve to various sections of the [stages vignette](https://lifecycle.r-lib.org/articles/stages) in the **lifecycle** package. It would be nice if these HTML manual pages could show the badges properly, or at least have some other way of showing the text "lifecycle: experimental/stable/superseded/deprecated" as appropriate. 

I'll also add this as an issue in the r-refmans repo.

**Comment by shikokuchuo** [comment]
We should look at the postdoc package by @jeroen.  https://cran.r-project.org/package=postdoc This has been producing the help manuals on R-universe for some time now.

The `dplyr` example has the lifecycle badges rendered perfectly: https://tidyverse.r-universe.dev/dplyr/doc/manual.html

**Comment by llrs** [comment]
# Work done

We found the IBM accessibility add-on for several browsers and the command line used [npm accessibility-checker](https://www.npmjs.com/package/accessibility-checker). We do not get the same notes with the terminal and the extension on the browser but mostly they are similar.

@Bisaloo also found the [nu HTML checker](https://validator.w3.org/nu/) and the [command line tool](https://github.com/validator/validator) but we had a problem to run that accessibility checker in the command line (didn't return anything). The online version found different issues than the other tool we had

We are checking the refmans inside the docs (we estimate we need 9 days with the accessibility check).
We compiled a table of common issues that would need fixing.
@eliocamp [created a patch](https://github.com/deepayan/r-refmans/issues/3#issuecomment-2225629669) to improved the CSS, and fix some issues:
 - tables only used for presentations.
 - missing space between ORCID = "adfaf"src="" in html
 - missing language declaration in the header of the file
 - Fix problem with low contrast code

# What's next

One big issue is the missing language that would need to be added or detected automatically and some have the DESCRIPTION in English but the help pages in Spanish (censo2017) or other different combinations of languages.
With a patch in progress this can be addressed, but help pages should have a field to use or a way to detected (we found the language can be set for only a portion of the HTML document), The patch assumes English but it would be better if we could check per html file. 

Another common issue is that user can tab to the code block with the function definitions. The solution would be to remove tabindex role. [This issue](https://github.com/deepayan/r-refmans/issues/3#issuecomment-2225487082) is harder to fix as it involves pulled javascript files.

We detected several issues that need careful decision, mostly
- https://github.com/deepayan/r-refmans/issues/7
- https://github.com/deepayan/r-refmans/issues/6

But mostly the are around >80% of the check used, we haven't checked postdoc but we could check how it fixes this issues (if it does).

**Comment by hturner** [comment]
Thanks for the summary. It is probably best to follow up via the issues on the [r-refmans repo](https://github.com/deepayan/r-refmans/) to allow more focused discussion and easier tracking. It may be helpful to raise a separate issue there about detecting language for individual help files?

I think we can close this as "done" for this Dev Day - if there is scope for contributors to help with specific solutions to issues raised these could be opened as new issues for future Dev Days (cc @deepayan)

**Comment by llrs** [comment]
Bioconductor might start creating reference manuals in html format soon.

I've submitted the updated patch to bugs.r-project.org: [18825](https://bugs.r-project.org/show_bug.cgi?id=18825). In the comment I also included the two other issues identified but not resolved.
