### ISSUE TITLE
Second-last step towards migrating from legacy (Kb, Mb, ...) to IEC (KiB, MiB, ...) units

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-devel/r-dev-day#28]
# Background

R uses home-made ("legacy") units for object and file sizes that, e.g.

```
> x <- double(1e12)
Error: cannot allocate vector of size 7450.6 Gb
```

Note that it uses 'Gb', which is actually _Gigabits_ (=1000^3 bits).
 It should really be using 'GiB' per the official IEC standard, which are defined as KiB (1024 bytes), MiB (1024^2 bytes), GiB (1024^3 bytes), TiB (1024^4 bytes).  FWIW, there is also an SI standard: kB (1000 bytes), MB (1000^2 bytes), GB (1000^3 bytes), TB (1000^4 bytes).

# Actions

Gist:

* [x] `utils:::format.object_size()` method already supports outputting legacy, IEC and SI units via argument `legacy`, `IEC`, and `SI`.
* [x] Identify functions that output strings with "legacy" units (mostly done)
* [x] Update above strings to use specific "unit string constants" instead of hard-coding the units, e.g. `error(_("cannot allocate memory block of size %0.f Tb"), size)` -> `error(_("cannot allocate memory block of size %0.f %s"), size, "Tb")`
* [x] Rebuild R and verify that above updates does not break anything, e.g. `make check`.

Special care has to be taken to avoid triggering additional memory allocations when producing these error messages. This is because in several cases these are triggered when we run out of memory.

After we know the above works as it should, it can be pushed to the R source. After this, we should:

* [ ] update translation messages to use `%s`, e.g. from `"cannot allocate memory block of size %0.f Tb"` to `"cannot allocate memory block of size %0.f %s"`

Eventually, we can switch to IEC units updating the above unit string constants to the IEC standard, e.g. `sed -i 's/"Tb"/"TiB"/'`.  

Note that with this strategy, if we later on would like to move from IEC to SI units, we don't have to update the message format strings and also not the translations - just the unit string constants and how we calculate the values.

# R-Core Member

* Martin Mächler (who approved on this strategy 2024-07-11)

# See also

For full background and more details, see https://github.com/HenrikBengtsson/Wishlist-for-R/issues/6.

**Comment by HenrikBengtsson** [comment]
# Patch

The following patch passes `make check-all`:

https://github.com/r-devel/r-svn/pull/171/files

**Comment by HenrikBengtsson** [comment]
On Bugzilla at https://bugs.r-project.org/show_bug.cgi?id=18297#c2.

**Comment by hturner** [comment]
Corresponding bug is now CLOSED FIXED :tada:

**Comment by hturner** [comment]
Note: the translation task is not suited to a Dev Day issue as we rarely have a broad range of languages represented at one event. This task could be promoted another way, e.g. in an online translatathon, or simply by contacting translation teams.
