### ISSUE TITLE
Bug 17839 - R_GetCurrentEnv() always returns the base namespace

### ISSUE THREAD

**Issue by shikokuchuo** [r-devel/r-dev-day#29]
https://bugs.r-project.org/show_bug.cgi?id=17839

It was added in the NEWS for R3.6.0:

R_GetCurrentEnv() allows C code to retrieve the current environment.

This is not the case, as highlighted in the bug report:

> The new `R_GetCurrentEnv()` function always returns the base namespace. That's because PP_FOREIGN primitives like `.Call()` create a context on the stack. The current implementation attempts to skip those by returning the `sysparent`, but both the `sysparent` and `cloenv` are set to the base namespace. The attached patch suggests a fix by skipping the non-closure contexts.

This leads to packages, such as `purrr` having to adopt ugly workarounds:
https://github.com/tidyverse/purrr/blob/fd5a7320e37f7301c2dcc1668d032ee0d35acc9c/src/conditions.c#L6-L34

There is a patch by @lionel- , tested myself last year.

Requires:
1. Acceptance by R-core
2. Re-test of patch against current R-devel

**Comment by ltierney** [comment]
I've added a note on Bugzilla that several of us would prefer to get rid of this function. We'll have to look into the impact that might have on package space.

**Comment by shikokuchuo** [comment]
Thanks Luke. This will help package authors inadvertently trying to use it in places where it doesn't do what they expect.

**Comment by hturner** [comment]
Closing as a Dev Day issue - any follow up can go on the Bugzilla report.
