### ISSUE TITLE
Global option for disabling forking

### ISSUE THREAD

**Issue by DavisVaughan** [r-devel/r-dev-day#31]
In IDEs like RStudio and Positron, we have historically gotten quite a few issues related to instability in forking / multicore processing.

It would be nice if there were a global option to _disable_ forking through the parallel package entirely. We are thinking this should be a global option rather than an environment variable, because typically we want to allow subprocesses started by the main process to still allow forking.

`?mcfork` even says:

> It is strongly discouraged to use mcfork and the higher-level functions which rely on it (e.g., mcparallel, mclapply and pvec) in GUI or embedded environments, because it leads to several processes sharing the same GUI which will likely cause chaos (and possibly crashes).

So hopefully this is something R core would be open to.

There seems to be only 1 place where the parallel package calls `fork()` - in `mc_fork()`:
https://github.com/wch/r-source/blob/f3903ef36b6b4469954df890a321caecd73688b9/src/library/parallel/src/fork.c#L563

So that is likely where the global option can be checked. If something like `options(parallel.disable_forking = TRUE)` has been set, then `mc_fork()` could throw an informative R error early on at the top of `mc_fork()`.

CC @lionel- and @georgestagg

**Comment by DavisVaughan** [comment]
CC @HenrikBengtsson

**Comment by Bisaloo** [comment]
Linking a previous issue where Henrik did some work & added more links:

https://github.com/HenrikBengtsson/Wishlist-for-R/issues/94
