### ISSUE TITLE
Automated linting of markdown documents via pre-commit and markdownlint-cli2

### ISSUE THREAD

**Issue by ns-rse** [r-devel/r-dev-day#65]
[Issue 194](https://github.com/r-devel/r-dev-env/issues/194) suggests linting the markdown documentation using [markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2) via a [pre-commit](https://pre-commit.com) hook and integrated via [pre-commit.ci](https://pre-commit.ci) so that checks are made when contributions are made.

**Comment by ns-rse** [comment]
See [Pull request #195](https://github.com/r-devel/r-dev-env/pull/195)

Thanks @hturner and @njtierney for running todays session. :+1:

**Comment by hturner** [comment]
Thanks for recording this work on the r-dev-day repo. We can follow up on your recommendations on the Dev Container repo.
