### ISSUE TITLE
Bug 18587 - Allow packages to supply alternate communication backends for the parallel package

### ISSUE THREAD

**Issue by shikokuchuo** [r-devel/r-dev-day#7]
[Bug 18587](https://bugs.r-project.org/show_bug.cgi?id=18587) - Allow packages to supply alternate communication backends for the `parallel` package

This is a remnant from the R Project Sprint 2023. The proposed code changes have already been committed by Luke Tierney (R Core).

The changes have been:

1.   Exporting (and hence officially making public) a set of previously internal S3 generics so that packages may supply their own methods, and
2.   A registration function so that the existing `parallel::makeCluster()` function can create these new cluster types (all entries were  previously hardcoded).

ACTION REQUIRED:

Provide documentation for the above changes in a new .Rd file.

There is already an attempt by Ivan Krylov for the first part of the change (in an attachment to the bug report). The main question here is determining what is appropriate to document / how to go about this, as different backends may make use of this new API in different ways.

Will require reading the entire bug report and attachments, and getting familiar with the contents. Everything is fairly self-contained.

I would greatly appreciate any discussion and insights to advance this and get it across the finish line.

**Comment by russHyde** [comment]
I emailed a version of the makeCluster.Rd manpage that includes a description of `parallel::registerClusterType()` to @shikokuchuo

**Comment by shikokuchuo** [comment]
I have also finished reviewing and tidying up the previous contribution from @aitap It is actually really good and I have made fairly minor modifications.

(@aitap I was at the airport when you posted your original contribution so I didn't give it the time I should have and misunderstood some of your effort).

I will check over again before replying to the bug report.

**Comment by shikokuchuo** [comment]
Thanks again @russHyde! I've just posted an update to the Bugzilla issue - comment 17 here: https://bugs.r-project.org/show_bug.cgi?id=18587

That completes this item from the R Project Sprint from my perspective. Will see what Luke has to say.
