### ISSUE TITLE
rdevday-en page link to 'labeled' issues may lack quotes

### ISSUE THREAD

**Issue by eddelbuettel** [r-devel/r-dev-day#82]
The [rdevday-en page](https://latinr.org/en/cronograma/r-dev-day/rdevday-en.html) has

> Tasks will be prepared as [issues on this repository with label LatinR2024](https://github.com/r-devel/r-dev-day/issues?q=is%3Aissue+is%3Aopen+label%3ALatinR2024).

but the link leads (ie https://github.com/r-devel/r-dev-day/issues?q=is%3Aissue+is%3Aopen+label%3ALatinR2024) leads to an empty report.   

Going the other way, ie starting from issues and selecting the label gets URL https://github.com/r-devel/r-dev-day/issues?q=is%3Aissue+is%3Aopen+label%3A%22LatinR+2024%22 -- leading to 18 issues.

**Comment by eddelbuettel** [comment]
Thanks for picking it up and rolling it over the three language pages.

**Comment by hturner** [comment]
Now fixed!
