### ISSUE TITLE
Bug 17988  - nlme::getGroupsFormula on corARMA gives 'form' argument must be a formula 

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-day#9]
In the discussion of [Bug 17988](https://bugs.r-project.org/show_bug.cgi?id=17988), R Core member @mmaechler proposes two actions:

1.  Abolish corIndent() objects
2. Give an error when corARMA(*) is called with p=q=0

The first of these has been implemented: corIdent() is deprecated in nlme version 3.1-162 (see entry dated 2023-01-28, https://svn.r-project.org/R-packages/trunk/nlme/ChangeLog). The second has not yet been implemented.

So we could create a patch implementing the second change:

- [x] Update nlme::corARMA() (in nlme/R/corStruct.R)
- [x] Update the help page: nlme/man/corARMA.Rd 
- [x] Run R CMD check on nlme with the updates
- [x] Create a patch and share it on the original bug report

Note that nlme is maintained in Subversion: https://svn.r-project.org/R-packages/trunk/nlme, so you will need Subversion installed to check out the repo and create a patch.

**Comment by thomaszwagerman** [comment]
In corStruct.R, changed corARMA() warning if p + q == 0, added a warning message to replace  deprecated `corIdent()` return:

```
  if (0 == (p + q)) {
    stop("at least one of p and q should be > 0. Use 'corAR1(0, *)' instead.")
  }
```

In help file corARMA.Rd, changed p & q item to:
```
 \item{p, q}{non-negative integers specifying respectively the
   autoregressive order and the moving average order of the \code{ARMA}
   structure. Both default to 0, but at least one should be > 0.}
```

**Comment by thomaszwagerman** [comment]
patch.diff submitted to the [bug report](https://bugs.r-project.org/show_bug.cgi?id=17988)

**Comment by hturner** [comment]
This bug is now CLOSED FIXED :tada:
